### ISSUE TITLE
Possible exceptions on BlazorWpfApp

### ISSUE THREAD

**Issue by Hyung-Kim** [edandersen/blazor-desktop-crossplatform-sample#1]
This project can not found default Path of WebviewAppShared. So, error raised when executing BlazorWpfApp.
Error message follows:
'Sorry, there's nothing at this address.'

**Comment by edandersen** [comment]
Is this just for the WPF app? Do the Web and WinForms versions work?

**Comment by ScionOfDesign** [comment]
I have the same issue. Only the web project works, the Wpf and WinForms apps show the 'Sorry, there's nothing at this address.' error.

**Comment by edandersen** [comment]
Looks like it needs updating for later Previews. Will take a look.

**Comment by edandersen** [comment]
Looks like this is a routing issue. Investigating.

**Comment by edandersen** [comment]
Updated the project to have a specific Home page and message.

**Comment by ScionOfDesign** [comment]
Thank you for updating it. I just checked it out and, while the homepage is shared, visiting any other page in the desktop app throws an exception:
![image](https://user-images.githubusercontent.com/8867456/133377082-54c04c3b-9db9-46d5-a274-cd68bf89e9cb.png)

**Comment by edandersen** [comment]
Hmm.. Thats interesting. I'll take another look tomorrow when I update this for .NET 6 RC1.

**Comment by edandersen** [comment]
I can't reproduce this. Please test with a fresh checkout, Visual Studio 2022 and .NET 6 RC1.

![image](https://user-images.githubusercontent.com/548636/133558560-7f5c31cf-5faa-427c-ad08-2b4e35e9cb65.png)

**Comment by ScionOfDesign** [comment]
Thanks, it was an issue with my VS instillation. I repaired it, deleted my cache, re-pulled, and now it works great! Fantastic work!
The ability to build cross-platform apps with the same code using Blazor is something I have been super excited about.
