### ISSUE TITLE
Sphere interaction doesn't work in WPF and WinForms

### ISSUE THREAD

**Issue by janseris** [edandersen/blazor-desktop-crossplatform-sample#7]
The interaction with sphere using mouse is not possible in any of the desktop variants. 
Works fine in browser.

**Comment by janseris** [comment]
I have found that using js from _content path repairs the sphere in desktop

**Comment by janseris** [comment]
Update:
this is sufficient - tested in the WinForms desktop project
when this line is edited, the sphere reacts to mouse again
![WebGL water sample fix](https://user-images.githubusercontent.com/64279914/156769391-0a9bf213-2d2c-415e-8bdb-7d2dd2e6f1ad.png)

**Comment by edandersen** [comment]
Fantastic, thank you. If you open a PR I'll merge it otherwise I'll get round to updating at some point. Thanks.
________________________________

**Comment by janseris** [comment]
Sadly, I don't know how to open a PR.
The button here is not active:
![image](https://user-images.githubusercontent.com/64279914/156773455-b7c89dc8-1763-4eab-8930-f7fe5e59425d.png)
And creating a new branch from my local code with fixes results in 403 Forbidden (access denied):
![image](https://user-images.githubusercontent.com/64279914/156773551-f5889755-8604-48f6-ace5-ba090ae89744.png)

**Comment by janseris** [comment]
The project with a new branch where resources are linked to shared wwwroot which fixes the issue is uploaded here instead of pull request:
https://easyupload.io/91t1xz
The file will be available for 30 days.

**Comment by edandersen** [comment]
Fantastic, this has also now been implemented. Thank you!
